set_property IOSTANDARD LVCMOS18 [get_ports clk_i]
set_property IOSTANDARD LVCMOS12 [get_ports rst]
set_property PACKAGE_PIN E18 [get_ports clk_i]
set_property PACKAGE_PIN p19 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports HDMI0_OE]
set_property IOSTANDARD LVDS [get_ports TMDSp_clock]
set_property IOSTANDARD LVDS [get_ports TMDSn_clock]
set_property PACKAGE_PIN T25 [get_ports TMDSp_clock]
set_property IOSTANDARD LVDS [get_ports {TMDSp[2]}]
set_property IOSTANDARD LVDS [get_ports {TMDSn[2]}]
set_property IOSTANDARD LVDS [get_ports {TMDSp[1]}]
set_property IOSTANDARD LVDS [get_ports {TMDSn[1]}]
set_property IOSTANDARD LVDS [get_ports {TMDSp[0]}]
set_property IOSTANDARD LVDS [get_ports {TMDSn[0]}]
set_property PACKAGE_PIN N24 [get_ports {TMDSp[0]}]
set_property PACKAGE_PIN V24 [get_ports {TMDSp[1]}]
set_property PACKAGE_PIN V23 [get_ports {TMDSp[2]}]
set_property PACKAGE_PIN Y16 [get_ports HDMI0_OE]

create_clock -period 20.000 [get_ports clk_i]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 51.0 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
 
set_property IOSTANDARD LVCMOS18 [get_ports LED]
set_property PACKAGE_PIN d18 [get_ports LED]
